[phases.setup]
nixpkgsArchive = '0d1ef1a839ce0f3282bf24bea2788b9ad659be83'
nixPkgs = ['...', 'nodejs']

[phases.install]
cmd = 'bun install --no-save'

[phases.build]
cmd = 'bun run build'

[start]
cmd = 'bun run start' 